name: mobil_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  audioplayers: ^6.4.0
  image_picker: ^0.8.7+5  # galeriden resim seçmek için
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/music.mp3  # bu dosyanın assets klasöründe olduğundan emin ol
